require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRailsVersion: 5.0
  TargetRubyVersion: 2.4
  NewCops: enable
  Exclude:
    - 'vendor/bundle/**/*'

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 23.75 # TODO: Lower to 15
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 8 # TODO: Lower to 6
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 19
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 9 # TODO: Lower to 7

Rails/HttpPositionalArguments:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false # Escaping chars helps with syntax highlighting
